package com.example.englishapp.model;

import java.io.Serializable;

public class SubtitleTrack implements Serializable {
    private String languageCode;
    private String languageName;
    private boolean isAutoGenerated;
    private String baseUrl;

    public SubtitleTrack(String languageCode, String languageName, boolean isAutoGenerated, String baseUrl) {
        this.languageCode = languageCode;
        this.languageName = languageName;
        this.isAutoGenerated = isAutoGenerated;
        this.baseUrl = baseUrl;
    }

    public String getLanguageCode() { return languageCode; }
    public String getLanguageName() { return languageName; }
    public boolean isAutoGenerated() { return isAutoGenerated; }
    public String getBaseUrl() { return baseUrl; }

    public String getDisplayName() {
        if (isAutoGenerated) {
            return languageName + " (auto-generated)";
        } else {
            return languageName;
        }
    }
}
