package com.example.englishapp.utils;

import android.util.Log;

import com.example.englishapp.model.Subtitle;
import com.example.englishapp.model.SubtitleTrack;
import com.example.englishapp.model.VideoInfo;

import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import org.json.JSONArray;
import org.json.JSONObject;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.TimeUnit;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * YouTubeSubtitleApi
 *
 * Lấy danh sách caption tracks và tải nội dung subtitle bằng cách
 * scrape watch-page (không cần OAuth2). Hỗ trợ cả JSON3 và SRV3/XML.
 *
 * Luồng hoạt động:
 *  1. getVideoInfo()  → scrape watch page → trả về danh sách SubtitleTrack có baseUrl
 *  2. getSubtitles()  → tải baseUrl (JSON3 hoặc XML) → trả về List<Subtitle>
 */
public class YouTubeSubtitleApi {

    private static final String TAG = "YouTubeSubtitleApi";

    // User-Agent Chrome 122 desktop – ít bị chặn nhất hiện tại
    private static final String UA =
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
            "(KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36";

    private final OkHttpClient client;

    public YouTubeSubtitleApi() {
        this.client = new OkHttpClient.Builder()
                .connectTimeout(30, TimeUnit.SECONDS)
                .readTimeout(30, TimeUnit.SECONDS)
                .followRedirects(true)
                .build();
    }

    // ─────────────────────────────────────────────────────────────────────────
    //  Callback interfaces
    // ─────────────────────────────────────────────────────────────────────────

    public interface VideoInfoCallback {
        void onSuccess(VideoInfo info);
        void onError(Exception e);
    }

    public interface SubtitlesCallback {
        void onSuccess(List<Subtitle> subtitles);
        void onError(Exception e);
    }

    // ─────────────────────────────────────────────────────────────────────────
    //  getVideoInfo: lấy tiêu đề + danh sách caption tracks
    // ─────────────────────────────────────────────────────────────────────────

    public void getVideoInfo(String videoId, VideoInfoCallback callback) {
        new Thread(() -> {
            try {
                // Lấy tiêu đề qua oEmbed (nhẹ, không cần API key)
                String title = fetchTitleViaOEmbed(videoId);

                String thumbnailUrl = "https://i.ytimg.com/vi/" + videoId + "/hqdefault.jpg";

                // Scrape watch page để lấy captionTracks
                String html = fetchWatchPage(videoId);
                if (html == null || html.isEmpty()) {
                    callback.onError(new IOException("Không thể tải trang xem video"));
                    return;
                }

                List<SubtitleTrack> tracks = extractCaptionTracks(html);

                if (tracks.isEmpty()) {
                    callback.onError(new Exception(""));
                } else {
                    callback.onSuccess(new VideoInfo(videoId, title, thumbnailUrl, tracks));
                }
            } catch (Exception e) {
                Log.e(TAG, "getVideoInfo error", e);
                callback.onError(e);
            }
        }).start();
    }

    // ─────────────────────────────────────────────────────────────────────────
    //  getSubtitles: tải nội dung subtitle theo track đã chọn
    // ─────────────────────────────────────────────────────────────────────────

    public void getSubtitles(String videoId, SubtitleTrack track, SubtitlesCallback callback) {
        new Thread(() -> {
            try {
                String baseUrl = track.getBaseUrl();

                // Nếu không có baseUrl, dùng timedtext API dự phòng
                if (baseUrl == null || baseUrl.isEmpty()) {
                    baseUrl = buildTimedtextUrl(videoId, track.getLanguageCode(),
                            track.isAutoGenerated() ? "asr" : "");
                }

                // Ưu tiên format JSON3 (dễ parse, chính xác timing)
                String fetchUrl = baseUrl.contains("fmt=") ? baseUrl : baseUrl + "&fmt=json3";

                String content = httpGet(fetchUrl);

                if (content == null || content.trim().isEmpty()) {
                    callback.onError(new IOException(""));
                    return;
                }

                List<Subtitle> subtitles;
                if (content.trim().startsWith("{")) {
                    subtitles = parseJson3(content);
                } else {
                    // Fallback: thử lại bằng XML (SRV3)
                    String xmlUrl = baseUrl.replaceAll("fmt=[^&]*", "").replaceAll("&$", "");
                    String xmlContent = httpGet(xmlUrl);
                    if (xmlContent == null) xmlContent = content;
                    subtitles = parseXml(xmlContent);
                }

                if (subtitles.isEmpty()) {
                    callback.onError(new Exception(""));
                } else {
                    Log.d(TAG, "getSubtitles OK: " + subtitles.size() + " dòng, lang=" + track.getLanguageCode());
                    callback.onSuccess(subtitles);
                }

            } catch (Exception e) {
                Log.e(TAG, "getSubtitles error", e);
                callback.onError(e);
            }
        }).start();
    }

    // ─────────────────────────────────────────────────────────────────────────
    //  Fetch watch page với headers đầy đủ
    // ─────────────────────────────────────────────────────────────────────────

    private String fetchWatchPage(String videoId) {
        // Thử nhiều variant URL để tránh redirect consent
        String[] urls = {
            "https://www.youtube.com/watch?v=" + videoId + "&hl=en&gl=US",
            "https://www.youtube.com/watch?v=" + videoId,
        };

        for (String url : urls) {
            try {
                String content = httpGet(url);
                if (content != null && content.contains("captionTracks")) {
                    Log.d(TAG, "Watch page chứa captionTracks: " + url);
                    return content;
                }
                if (content != null && content.length() > 10000) {
                    // Có nội dung nhưng không có subtitles – video có thể ko có sub
                    Log.d(TAG, "");
                    return content;
                }
            } catch (Exception e) {
                Log.w(TAG, "fetchWatchPage failed for " + url + ": " + e.getMessage());
            }
        }
        return null;
    }

    // ─────────────────────────────────────────────────────────────────────────
    //  HTTP GET với đầy đủ headers giống browser
    // ─────────────────────────────────────────────────────────────────────────

    String httpGet(String url) throws IOException {
        Request request = new Request.Builder()
                .url(url)
                .addHeader("User-Agent", UA)
                .addHeader("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8")
                .addHeader("Accept-Language", "en-US,en;q=0.9,vi;q=0.8")
                .addHeader("Accept-Encoding", "identity")
                .addHeader("Cache-Control", "no-cache")
                .addHeader("Cookie", "CONSENT=YES+cb; SOCS=CAESEwgDEgk4ME9BU1BiZxoCdmlFLS11bmRlcmxheQ==; GPS=1")
                .build();

        Response response = client.newCall(request).execute();
        int code = response.code();
        Log.d(TAG, "GET " + url.substring(0, Math.min(100, url.length())) + " → " + code);

        if (!response.isSuccessful()) {
            if (response.body() != null) response.body().close();
            throw new IOException("HTTP " + code);
        }

        String body = response.body() != null ? response.body().string() : null;
        if (body != null) Log.d(TAG, "Response: " + body.length() + " chars");
        return body;
    }

    // ─────────────────────────────────────────────────────────────────────────
    //  Fetch tiêu đề video qua oEmbed (miễn phí, không cần API key)
    // ─────────────────────────────────────────────────────────────────────────

    private String fetchTitleViaOEmbed(String videoId) {
        try {
            String oEmbedUrl = "https://www.youtube.com/oembed?url=https://youtube.com/watch?v="
                    + videoId + "&format=json";
            String resp = httpGet(oEmbedUrl);
            if (resp != null) {
                JSONObject json = new JSONObject(resp);
                return json.optString("title", "Video " + videoId);
            }
        } catch (Exception e) {
            Log.w(TAG, "oEmbed title fetch failed: " + e.getMessage());
        }
        return "Video " + videoId;
    }

    // ─────────────────────────────────────────────────────────────────────────
    //  Extract caption tracks từ HTML watch page
    //  Thử 3 strategy: regex captionTracks, ytInitialPlayerResponse JSON, innerHTML search
    // ─────────────────────────────────────────────────────────────────────────

    List<SubtitleTrack> extractCaptionTracks(String html) {
        List<SubtitleTrack> tracks = new ArrayList<>();

        // ── Strategy 1: regex "captionTracks":[...]
        try {
            Pattern p = Pattern.compile("\"captionTracks\":\\[([^\\]]+)\\]");
            Matcher m = p.matcher(html);
            if (m.find()) {
                JSONArray arr = new JSONArray("[" + m.group(1) + "]");
                parseCaptionTracksArray(arr, tracks);
                if (!tracks.isEmpty()) {
                    Log.d(TAG, "Strategy 1 OK: " + tracks.size() + " tracks");
                    return tracks;
                }
            }
        } catch (Exception e) {
            Log.w(TAG, "Strategy 1 failed: " + e.getMessage());
        }

        // ── Strategy 2: parse ytInitialPlayerResponse JSON object
        try {
            int idx = html.indexOf("ytInitialPlayerResponse");
            if (idx >= 0) {
                // Tìm { sau dấu =
                int start = html.indexOf('{', idx);
                if (start >= 0) {
                    // Đếm ngoặc để tìm cuối JSON object
                    int depth = 0;
                    int end = start;
                    for (; end < html.length() && end < start + 500000; end++) {
                        char c = html.charAt(end);
                        if (c == '{') depth++;
                        else if (c == '}') {
                            depth--;
                            if (depth == 0) break;
                        }
                    }
                    if (depth == 0) {
                        JSONObject playerResp = new JSONObject(html.substring(start, end + 1));
                        JSONObject captions = playerResp.optJSONObject("captions");
                        if (captions != null) {
                            JSONObject renderer = captions.optJSONObject("playerCaptionsTracklistRenderer");
                            if (renderer != null) {
                                JSONArray arr = renderer.optJSONArray("captionTracks");
                                if (arr != null) {
                                    parseCaptionTracksArray(arr, tracks);
                                    if (!tracks.isEmpty()) {
                                        Log.d(TAG, "Strategy 2 OK: " + tracks.size() + " tracks");
                                        return tracks;
                                    }
                                }
                            }
                        }
                    }
                }
            }
        } catch (Exception e) {
            Log.w(TAG, "Strategy 2 failed: " + e.getMessage());
        }

        // ── Strategy 3: tìm baseUrl trực tiếp trong HTML
        try {
            Pattern urlPattern = Pattern.compile("\"baseUrl\":\"(https://www\\.youtube\\.com/api/timedtext[^\"]+)\"");
            Matcher m = urlPattern.matcher(html);
            while (m.find()) {
                String baseUrl = m.group(1).replace("\\u0026", "&").replace("\\/", "/");
                // Parse language code từ URL
                String lang = "en";
                Matcher langM = Pattern.compile("[?&]lang=([^&]+)").matcher(baseUrl);
                if (langM.find()) lang = langM.group(1);
                boolean isAsr = baseUrl.contains("kind=asr");
                String displayName = lang + (isAsr ? " (Auto)" : "");
                tracks.add(new SubtitleTrack(lang, displayName, isAsr, baseUrl));
            }
            if (!tracks.isEmpty()) {
                Log.d(TAG, "Strategy 3 OK: " + tracks.size() + " tracks");
            }
        } catch (Exception e) {
            Log.w(TAG, "Strategy 3 failed: " + e.getMessage());
        }

        return tracks;
    }

    private void parseCaptionTracksArray(JSONArray arr, List<SubtitleTrack> out) throws Exception {
        for (int i = 0; i < arr.length(); i++) {
            JSONObject obj = arr.getJSONObject(i);
            String baseUrl = obj.optString("baseUrl", "");
            if (baseUrl.isEmpty()) continue;

            // Unescape unicode sequences trong baseUrl
            baseUrl = baseUrl.replace("\\u0026", "&").replace("\\/", "/");

            String langCode = obj.optString("languageCode", "en");

            // Lấy tên hiển thị
            String displayName = langCode;
            JSONObject nameObj = obj.optJSONObject("name");
            if (nameObj != null) {
                String simple = nameObj.optString("simpleText", "");
                if (!simple.isEmpty()) {
                    displayName = simple;
                } else {
                    JSONArray runs = nameObj.optJSONArray("runs");
                    if (runs != null && runs.length() > 0) {
                        displayName = runs.getJSONObject(0).optString("text", langCode);
                    }
                }
            }

            boolean isAsr = "asr".equals(obj.optString("kind", ""));
            if (isAsr) displayName += " (Tự động)";

            out.add(new SubtitleTrack(langCode, displayName, isAsr, baseUrl));
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    //  Timedtext URL dự phòng (không cần baseUrl)
    // ─────────────────────────────────────────────────────────────────────────

    private String buildTimedtextUrl(String videoId, String lang, String kind) {
        StringBuilder sb = new StringBuilder("https://www.youtube.com/api/timedtext?v=")
                .append(videoId)
                .append("&lang=").append(lang)
                .append("&fmt=json3");
        if (!kind.isEmpty()) sb.append("&kind=").append(kind);
        return sb.toString();
    }

    // ─────────────────────────────────────────────────────────────────────────
    //  Parse JSON3 format (YouTube's internal caption format)
    //  Format: {"events":[{"tStartMs":1000,"dDurationMs":2000,"segs":[{"utf8":"..."}]}]}
    // ─────────────────────────────────────────────────────────────────────────

    List<Subtitle> parseJson3(String json) {
        List<Subtitle> result = new ArrayList<>();
        try {
            if (json.startsWith("\uFEFF")) json = json.substring(1); // Strip BOM
            JSONObject root = new JSONObject(json);
            JSONArray events = root.optJSONArray("events");
            if (events == null) {
                Log.w(TAG, "JSON3 không có 'events'");
                return result;
            }

            for (int i = 0; i < events.length(); i++) {
                JSONObject ev = events.getJSONObject(i);
                if (!ev.has("segs")) continue;

                long startMs = ev.optLong("tStartMs", -1);
                long durMs = ev.optLong("dDurationMs", 0);
                if (startMs < 0) continue;

                JSONArray segs = ev.getJSONArray("segs");
                StringBuilder sb = new StringBuilder();
                for (int j = 0; j < segs.length(); j++) {
                    String utf8 = segs.getJSONObject(j).optString("utf8", "");
                    if (!"\n".equals(utf8)) sb.append(utf8);
                }

                String text = sb.toString().trim();
                if (text.isEmpty()) continue;

                float startSec = startMs / 1000f;
                float endSec = (startMs + (durMs > 0 ? durMs : 2500)) / 1000f;
                result.add(new Subtitle(text, startSec, endSec));
            }

            Log.d(TAG, "parseJson3: " + result.size() + " subtitle entries");
        } catch (Exception e) {
            Log.e(TAG, "parseJson3 error: " + e.getMessage());
        }
        return result;
    }

    // ─────────────────────────────────────────────────────────────────────────
    //  Parse XML/SRV3 format
    //  Format: <text start="1.0" dur="2.0">Hello world</text>
    // ─────────────────────────────────────────────────────────────────────────

    List<Subtitle> parseXml(String xml) {
        List<Subtitle> result = new ArrayList<>();
        try {
            Document doc = Jsoup.parse(xml, "", org.jsoup.parser.Parser.xmlParser());
            Elements textElements = doc.select("text");
            for (Element element : textElements) {
                try {
                    String startStr = element.attr("start");
                    String durStr = element.attr("dur");
                    float startSec = startStr.isEmpty() ? 0 : Float.parseFloat(startStr);
                    float durSec = durStr.isEmpty() ? 2.0f : Float.parseFloat(durStr);
                    // Jsoup decode HTML entities tự động (e.g. &amp; → &)
                    String text = element.text().trim();
                    if (!text.isEmpty()) {
                        result.add(new Subtitle(text, startSec, startSec + durSec));
                    }
                } catch (Exception ignored) { /* skip element lỗi */ }
            }
            Log.d(TAG, "parseXml: " + result.size() + " subtitle entries");
        } catch (Exception e) {
            Log.e(TAG, "parseXml error: " + e.getMessage());
        }
        return result;
    }
}
